freebsd_instance:
  image_family: freebsd-13-2
task:
  install_script:
    # Update all packages
    - pkg update -f
    - pkg upgrade -f -y
    - pkg install -y cmake hdf5
  configure_script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
  build_script:
    - cmake --build build -- -j8
  test_script: |
    for file in ./share/*.mat; do
      ./build/matdump -d "$file" d
      ./build/matdump -v "$file"
      ./build/matdump -v -f whos "$file"
    done
    ./build/matdump -v -H
    ./build/matdump -V
