freebsd_instance:
  image_family: freebsd-14-2
task:
  install_script:
    # Update all packages
    - env IGNORE_OSVERSION=yes pkg update -f
    - pkg upgrade -f -y
    - pkg install -y cmake git hdf5
    - git submodule update --init
  configure_script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
  build_script:
    - cmake --build build -- -j8
  test_script:
    - ctest --no-tests=error --test-dir build --build-config Release --parallel 8
