#! /bin/sh
#  reconfig
#    Runs configure scripts

DEFAULT_OPTS="--prefix=$HOME --exec-prefix=$HOME"

cd zlib
CC=gcc \
CFLAGS='-DZ_PREFIX -v -g -fPIC -fexceptions' \
LDFLAGS='-fexceptions' \
./configure $DEFAULT_OPTS
make
make install
make clean
cd ..

cd build-solaris
DEBUG="--enable-debug"
ZLIB_OPTS="--with-zlib=$HOME"
DOCS_OPTS="--with-docs=no"
FORTRAN="--enable-fortran=no"
CC=gcc \
CFLAGS='-Wall -pedantic -fPIC -fexceptions' \
LDFLAGS='-fexceptions' \
../configure CC=gcc FC= CFLAGS="$CFLAGS" FCFLAGS="$FCFLAGS" LDFLAGS="$LDFLAGS" \
    $DEFAULT_OPTS $DEBUG $FORTRAN $ZLIB_OPTS $DOCS_OPTS

if test $? = 0
then
    make && make install
fi

cd ..
