#! /bin/sh
#  reconfig
#    Runs configure scripts

DEFAULT_OPTS="--prefix=$HOME --exec-prefix=$HOME"

cd zlib
CC=gcc \
CFLAGS='-mno-cygwin -DZ_PREFIX -v -g -fPIC' \
LDFLAGS='-fexceptions' \
./configure $DEFAULT_OPTS
make && make install && make clean
cd ..

cd build-mingw
ZLIB_OPTS="--with-zlib=$HOME"
DOCS_OPTS="--with-docs=no"
FORTRAN="--enable-fortran=no"
CFLAGS=''
FCFLAGS=''
LDFLAGS=''
../configure CC=gcc FC= CFLAGS="$CFLAGS" FCFLAGS="$FCFLAGS" LDFLAGS="$LDFLAGS" $DEFAULT_OPTS $ZLIB_OPTS $FORTRAN $DOCS_OPTS

if test $? = 0
then
    make && make install
fi

cd ..
