#! /bin/sh
##
## Run this script to build matio on Linux
##
## Copyright (C) 2005-2006   Christopher C. Hulbert
##
##  This library is free software; you can redistribute it and/or
##  modify it under the terms of the GNU Lesser General Public
##  License as published by the Free Software Foundation; either
##  version 2.1 of the License, or (at your option) any later version.
##
##  This library is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
##  Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public
##  License along with this library; if not, write to the Free Software
##  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##

DEFAULT_OPTS="--prefix=$HOME --exec-prefix=$HOME"

cd zlib
CC=gcc \
CFLAGS='-DZ_PREFIX -v -g -fPIC -fexceptions' \
LDFLAGS='-fexceptions' \
./configure $DEFAULT_OPTS
make
make install
make clean
cd ..

cd build-solaris
DEBUG="--enable-debug"
ZLIB_OPTS="--with-zlib=$HOME"
DOCS_OPTS="--with-docs=no"
FORTRAN="--enable-fortran=no"
CC=gcc \
CFLAGS='-Wall -pedantic -fPIC -fexceptions' \
LDFLAGS='-fexceptions' \
../configure CC=gcc FC= CFLAGS="$CFLAGS" FCFLAGS="$FCFLAGS" LDFLAGS="$LDFLAGS" \
    $DEFAULT_OPTS $DEBUG $FORTRAN $ZLIB_OPTS $DOCS_OPTS

if test $? = 0
then
    make && make install
fi

cd ..
