.\" Copyright (c) 2015-2026, The matio contributors
.\" Copyright (c) 2012-2014, Christopher C. Hulbert
.\" All rights reserved.
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd March 14, 2012
.Dt MAT_VARGETSTRUCTSLINEAR 3
.Os
.Sh NAME
.Nm Mat_VarGetStructsLinear
.Nd Linearly index a structure variable
.Sh SYNOPSIS
.Fd #include <matio.h>
.Ft matvar_t *
.Fo Mat_VarGetStructsLinear
.Fa "const matvar_t *matvar"
.Fa "int start"
.Fa "int stride"
.Fa "int edge"
.Fa "int copy_fields"
.Fc
.Sh DESCRIPTION
The
.Fn Mat_VarGetStructsLinear
function selects a subarray from a structure array
.Fa matvar.
Each of the elements in the subarray contains all of the fields of the
structure.
The indexing starts at the
.Fa start
element in the array (0 being the first element), and reads every
.Fa stride
values (1 being every element, 2 every other element, etc.). The total number
of elements in the subarray is specified as
.Fa edge.
The original array must have at least
.Fa start+(stride-1)*edge+1
elements.
The
.Fa copy_fields
option specifies whether the fields of the original structure are copied for
the new subarray.
If set to 0, the returned structure array's fields have the same pointer as the
original array, and the
.Dv data
field of the subarray structure.
The subarray is marked with the conserve memory flag indicating that the fields
should not be free'd.
They are free'd when the original structure is free'd.
.Sh RETURN VALUES
A subarray of the original structure array, or NULL if there is an error.
.Sh SEE ALSO
.Xr Mat_VarGetStructs 3
