.\" Copyright (c) 2015-2026, The matio contributors
.\" Copyright (c) 2012-2014, Christopher C. Hulbert
.\" All rights reserved.
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd March 18, 2012
.Dt MAT_VARFREE 3
.Os
.Sh NAME
.Nm Mat_VarFree
.Nd Frees a MAT variable structure.
.Sh SYNOPSIS
.Fd #include <matio.h>
.Ft void
.Fo Mat_VarFree
.Fa "matvar_t *matvar"
.Fc
.Sh DESCRIPTION
The
.Fn Mat_VarFree
function free's the memory used by a MAT variable structure.
If the variable was not created with the
.Dv MAT_F_DONT_COPY_DATA
flag, the variable data is also free'd.
.Sh SEE ALSO
.Xr Mat_VarCreate 3 ,
.Xr Mat_VarCreateStruct 3
