.\" Copyright (c) 2015-2026, The matio contributors
.\" Copyright (c) 2012-2014, Christopher C. Hulbert
.\" All rights reserved.
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd March 18, 2012
.Dt MAT_VARADDSTRUCTFIELD 3
.Os
.Sh NAME
.Nm Mat_VarAddStructField
.Nd Adds a field to a structure array.
.Sh SYNOPSIS
.Fd #include <matio.h>
.Ft int
.Fo Mat_VarAddStructField
.Fa "matvar_t *matvar"
.Fa "const char *fieldname"
.Fc
.Sh DESCRIPTION
The
.Fn Mat_VarAddStructField
function adds a fieldname to the structure variable
.Fa matvar.
.Sh RETURN VALUES
0 is returned on success.
.Sh SEE ALSO
.Xr Mat_VarCreateStruct 3
