.\" Copyright (c) 2015-2026, The matio contributors
.\" Copyright (c) 2011-2014, Christopher C. Hulbert
.\" All rights reserved.
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd September 12, 2019
.Dt MAT_CLOSE 3
.Os
.Sh NAME
.Nm Mat_Close
.Nd Closes an open MATLAB MAT file.
.Sh SYNOPSIS
.Fd #include <matio.h>
.Ft int
.Fo Mat_Close
.Fa "mat_t *matfp"
.Fc
.Sh DESCRIPTION
The
.Fn Mat_Close
function closes a MATLAB MAT file opened with
.Fn Mat_Open
or created with
.Fn Mat_CreateVer .
.Sh RETURN VALUES
The function returns 0 on success.
Otherwise, an error value is returned.
.Sh EXAMPLES
.Bd -literal
#include "matio.h"

int main(int argc, char **argv)
{
    mat_t *matfp;

    matfp = Mat_Open(argv[1], MAT_ACC_RDONLY);
    if ( NULL == matfp ) {
        fprintf(stderr, "Error opening MAT file %s\n", argv[1]);
        return EXIT_FAILURE;
    }

    Mat_Close(matfp);
    return EXIT_SUCCESS;
}

.Ed
.Sh SEE ALSO
.Xr Mat_Open 3 ,
.Xr Mat_CreateVer 3
