.\" Copyright (c) 2012-2016 Christopher C. Hulbert
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY CHRISTOPHER C. HULBERT ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL CHRISTOPHER C. HULBERT OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd March 12, 2012
.Dt MAT_GETVERSION 3
.Os
.Sh NAME
.Nm Mat_GetVersion
.Nd Returns the version of a MATLAB .mat file given a MAT file structure
.Sh SYNOPSIS
.Fd #include <matio.h>
.Ft enum mat_ft
.Fo Mat_GetVersion
.Fa "mat_t *matfp"
.Fc
.Sh DESCRIPTION
The
.Fn Mat_GetVersion
function returns the version of the MATLAB .mat file given by the MAT file
structure. The return value is one of the following:
.Bl -bullet
.It
.Cm MAT_FT_MAT73
if the file is an HDF5 MAT file.
.It
.Cm MAT_FT_MAT5
if the file is a level 5 MAT file.
.It
.Cm MAT_FT_MAT4
if the file is a level 4 MAT file.
.El
.Sh SEE ALSO
.Xr Mat_Create 3 ,
.Xr Mat_CreateVer 3 ,
.Xr Mat_Open 3
.Xr Mat_GetFilename 3
