.\" Copyright (c) 2015-2026, The matio contributors
.\" Copyright (c) 2012-2014, Christopher C. Hulbert
.\" All rights reserved.
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd April 23, 2026
.Dt MAT_LOGINIT 3
.Os
.Sh NAME
.Nm Mat_LogInit
.Nd Initializes matio logging with the default logger.
.Sh SYNOPSIS
.Fd #include <matio.h>
.Ft int
.Fo Mat_LogInit
.Fa "const char *prog_name"
.Fc
.Sh DESCRIPTION
The
.Fn Mat_LogInit
function installs the default matio logging callback and records
.Fa prog_name
for log message prefixes.
It also resets verbose and silent logging state.
.Sh RETURN VALUES
The function returns 0.
.Sh SEE ALSO
.Xr Mat_LogClose 3 ,
.Xr Mat_LogInitFunc 3